### ISSUE TITLE
www.ReactiveX.io Website

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/reactivex.github.io#1]
This issue is intended to kickoff the discussion of what the www.reactivex.io website should include and get the work started on it.

-------

- Intro, what it is, what it solves, why it exists.
	- how to get started quickly
	- dependency management for each language and hello world
	- links to latest releases for each language
- Documentation
	- common across all languages 
		- existing documentation for RxJava (https://github.com/Netflix/RxJava/wiki) and RxJS (https://github.com/Reactive-Extensions/RxJS/tree/master/doc) can hopefully be used as a starting point and come together somehow
		- we want a mechanism for docs to be written and maintained in Github and show up nicely formatted on the site (does not need to keep leveraging the wiki though, can be Markdown or other formatted files in the site repo)
	- language specific details
	- each operator can have the common marble diagrams, then per-language examples, idioms, synonyms, etc
- Languages
	- list of languages with news, release notes, documentation etc specific to each implementation
- Related Projects
	- other projects that are not Rx implementations, but related to it … projects that use or leverage Rx
- Media
	- presentations, talks, conferences etc
- Community
	- google groups, twitter etc
- Github
	- github.com/ReactiveX for all code, issues, etc for each language
- Releases and Binaries
	- Apache (eventually)

Here are example sites:

http://vertx.io (particular see how code examples are done for each language)
http://netty.io
http://www.ratpack.io
http://akka.io
http://emberjs.com
http://angularjs.org
http://spark.apache.org

**Comment by DavidMGross** [comment]
Closing this one out; if there are unfinished subtasks, please file new issues specific to them.
