### ISSUE TITLE
GitHub API Rate Limit

### ISSUE THREAD

**Issue by GeorgiKhomeriki** [ReactiveX/reactivex.github.io#11]
The [GitHub API rate limit](https://developer.github.com/v3/#rate-limiting) might become a problem for the dynamic code examples (loaded client-side).
The API allows only 60 requests per hour for unregistered users...
Registered users are permitted to do 5000 requests per hour, but that would require user authentication (Basic/OAuth).

**Comment by DavidMGross** [comment]
Please discuss this on Issue #99 at least so far as it pertains to dynamic code examples.
