### ISSUE TITLE
Make "develop" branch the default branch, rather than "master"

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/reactivex.github.io#124]
I don't have sufficient permissions to do this, I don't think.  @benjchristensen maybe?

We do our site development in "develop" and then periodically generate the site locally using rake before checking it in to the "master" branch -- that is to say, nobody should be checking in incremental changes to "master."

New contributors are confused by this and often try to alter "master" directly as it's the default branch.

**Comment by benjchristensen** [comment]
Done.
