### ISSUE TITLE
Interactive marble diagrams

### ISSUE THREAD

**Issue by staltz** [ReactiveX/reactivex.github.io#13]
One basic question: where should the interactive marble diagrams be placed on the website? Under a dedicated section? One interactive diagram under each documented operator? Somewhere else?

That's important to know because it affects how I should adapt http://staltz.github.io/rxmarbles to this website.

**Comment by staltz** [comment]
I'm this `> <` close to making a web component `<x-rxmarbles key="debounce">` for RxMarbles, enabling a very easy way to embed it in this website's docs.

More news very soon.

**Comment by DavidMGross** [comment]
[Like]

On Sat, Feb 7, 2015 at 9:10 AM, André Staltz <notifications@github.com>
wrote:

> I'm this > < close to making a web component <x-rxmarbles key="debounce">
> for RxMarbles, enabling a very easy way to embed it in this website's docs.
>
> More news very soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/issues/13#issuecomment-73372793>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by benjchristensen** [comment]
Sounds great!

**Comment by staltz** [comment]
Done in PR #87 

Looks like this:
![screen shot 2015-02-08 at 16 40 15](https://cloud.githubusercontent.com/assets/90512/6096937/dd67fc80-afb1-11e4-9d46-061d64654ec7.png)

Just like RxMarbles.com, it doesn't have all the operators since some are more complicated (observable of observables, or contains an error, etc). But works like a charm as a Web Component.

Related https://github.com/staltz/rxmarbles/issues/1

**Comment by benjchristensen** [comment]
Very nice.

**Comment by staltz** [comment]
It's merged into develop, so I think I'll close this one. We can do continuous improvements through other issues. Such as #88
