### ISSUE TITLE
Change "Essence and origins of FRP" link

### ISSUE THREAD

**Issue by conal** [ReactiveX/reactivex.github.io#136]
First, thank you *very* much for including the clarification that FRP and ReactiveX are very different animals, and including a link to my "Essence and origins of FRP" talk slides. If you would you do me the additional kindness of changing that link to https://github.com/conal/essence-and-origins-of-frp, then people can find not only the slides PDF but also the abstract, video(s), and more recent versions of the talk, particularly from Lambda Jam 2015.

**Comment by conal** [comment]
Thanks again! Will the change propagate to http://reactivex.io/intro.html soon?

**Comment by DavidMGross** [comment]
It will at the next update (these happen at irregular intervals).

On Wed, Aug 26, 2015 at 1:41 PM, Conal Elliott <notifications@github.com>
wrote:

> Thanks again! Will the change propagate to http://reactivex.io/intro.html
> soon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/issues/136#issuecomment-135164662>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by conal** [comment]
Thanks for the explanation. It's now propagated.
