### ISSUE TITLE
"See Also" misplaced in centre of decision tree

### ISSUE THREAD

**Issue by whymarrh** [ReactiveX/reactivex.github.io#145]
There seems to be a misplaced "See Also":

!["See Also" misplaced in page](https://cloud.githubusercontent.com/assets/1623628/9772724/9911f1e4-5718-11e5-97b7-c68129ca8be4.png)

**Comment by DavidMGross** [comment]
Thanks for letting us know.

**Comment by DavidMGross** [comment]
Fix in commit #789b02f... should roll out to the live site before too long.
