### ISSUE TITLE
Move Rx.PHP to the ReactiveX organisation?

### ISSUE THREAD

**Issue by asm89** [ReactiveX/reactivex.github.io#149]
Not sure what's the best forum to discuss this, but this repository seemed the most appropriate.

Two years ago I released a first version of [Rx.PHP](https://github.com/asm89/Rx.PHP) (started as a course project following a course by @headinthebox). Over time the project has proved a stable base and more recently people have started contributing new features and improvements to the library (lift operator, bridge with popular promise implementation in PHP). The new contributions made me reflect on the fact that I've been supporting the library from my personal user account at GitHub, but now things are getting more mature I wonder what would it take to continue development of Rx.PHP under the ReactiveX organization?

cc @benjchristensen @JakeWharton @kzaher @stevegury @zsxwing (public members of the organization at https://github.com/ReactiveX, please help me in pinging other people where appropriate)

cc @davidwdan @mbonneau (recent Rx.PHP contributors)

**Comment by headinthebox** [comment]
Submit a pull request and we'll gladly add it!

**Comment by asm89** [comment]
@headinthebox If I were to continue development under the ReactiveX organization, then I need a new repository with push rights to push the code to. :)

**Comment by benjchristensen** [comment]
Do you want a new repo (RxPhp) to start from scratch? Or do you want to migrate your existing one?

If migrating, we can get together in chat to handle the permissions needed together. If new, I can set it up, grant all privileges, and you can do whatever you want. Generally migration is wanted as it retains all stars, forks, watchers, etc.

**Comment by benjchristensen** [comment]
Also, the normal naming convention would be RxPHP, like RxJS and RxJava.

**Comment by asm89** [comment]
Let's try a proper migration. :+1: I'm keen on renaming to RxPHP, but I have to figure out how that fits in the migration thing (e.g. rename first, then migrate or the other way around).

**Comment by benjchristensen** [comment]
@asm89 and I just spoke and he now has privileges to become part of ReactiveX and do the migration.

**Comment by headinthebox** [comment]
Like! PHP for world dominance.

**Comment by DavidMGross** [comment]
Looks like this is a done deal.
