### ISSUE TITLE
Double-check documentation & diagrams for throttleFirst

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/reactivex.github.io#159]
...in light of the discussion at ReactiveX/RxJava#3529 and ReactiveX/RxJava#3636

**Comment by DavidMGross** [comment]
I think I've got the diagrams fixed, but the write-up still needs looking over.

**Comment by akarnokd** [comment]
I think the following diagram should indicate that if there are no values beyond the time limit, nothing happens and the timer starts at the next value only:

![image](https://cloud.githubusercontent.com/assets/1269832/16143341/64960892-346c-11e6-831d-5e0507c42b60.png)

**Comment by DavidMGross** [comment]
Would eliminating the orange marble do the job, do you think?

On Wed, Jun 22, 2016 at 6:06 AM, David Karnok <notifications@github.com>
wrote:

> I think the following diagram should indicate that if there are no values
> beyond the time limit, nothing happens and the timer starts at the next
> value only:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1269832/16143341/64960892-346c-11e6-831d-5e0507c42b60.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/issues/159#issuecomment-227736994>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AESHoM9pH1msyOdj-CrU5wKOY7SwADoLks5qOTNRgaJpZM4GsqGO>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by akarnokd** [comment]
Yes.
