### ISSUE TITLE
Rx inspired what programming languages?

### ISSUE THREAD

**Issue by dlazerka** [ReactiveX/reactivex.github.io#174]
Main page http://reactivex.io/ says that it inspired `even programming languages`. But I couldn't find anything on that. What programming languages is it about? Would be nice to hyperlink it.

**Comment by staltz** [comment]
dart lang

**Comment by nelsonlaquet** [comment]
How so?

**Comment by dbrattli** [comment]
https://dart.dev/tutorials/language/streams
