### ISSUE TITLE
Documentation and Navigation

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/reactivex.github.io#20]
Right now the documentation is too implementation specific. 

For example, this page assumes RxJava: http://reactivex.io/documentation.html  ... particularly in how it puts binaries as the first thing being shown.

Right from the start this page needs to include at least RxJS and RxJava.

I suggest we start with just a simple page with links to existing RxJS, RxJava and soon to arrive documentation from RxScala, RxAndroid etc.

Then we can start to shape it into this new model

I'd like to use this site as the landing page now even though we don't have the docs in place.

**Comment by DavidMGross** [comment]
Closing this issue as it's gotten unwieldy. I shuffled one major unfinished bit off into Issue #99. If there are any other issues lingering here that I missed and that need to be addressed, please open a new issue for them.
