### ISSUE TITLE
document how to use a/syncOnSubscribe

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/reactivex.github.io#221]
see ReactiveX/RxJava#3780

"I couldn't find a detailed documentation on how to use these onSubscribe, other than the javadoc, after a quick search. Can you suggest a pointer to such resources if they exist? If they don't exist, could promoting these to BETA include some detailed piece of documentation, like a wiki page giving examples on how and when to use the AsyncOnSubscribe and SyncOnSubscribe?" - Simon Baslé

**Comment by akarnokd** [comment]
These have been removed from later RxJava versions.
