### ISSUE TITLE
Who uses ReactiveX

### ISSUE THREAD

**Issue by staltz** [ReactiveX/reactivex.github.io#26]
On the frontpage, I'm planning to include a section "Who uses Rx" listing a few companies that use Rx in a significant way or as a core technology. My memory is very bad at the moment and honestly I can just think of Netflix and Couchbase.

So, could you guys list a few more so I can fill this list?

UPDATE:

**If you wish to have your companies' logo and link on the frontpage, just provide a png image of size approx. 500x200 (or better), with white or transparent background, and a link to the page. We can include logos as much as there is incoming, but at some amount (maybe 12?), we should reconsider which ones are stronger for social proof.**

Logos will be sorted by decreasing Alexa ranking (global), and with a max of 12 logos on the frontpage.
Current sorting as of 19 September 2014:
1. Microsoft (42)
2. Netflix (81)
3. GitHub (133)
4. SoundCloud (180)
5. Trello (531)
6. Treehouse (2,224)
7. SeatGeek (14,258)
8. ooVoo (24,278)
9. Couchbase (49,285)
10. Futurice (385,110)
11. Welbe (1,573,204)

**Comment by tonycosentini** [comment]
@staltz are you still accepting logo submissions via this thread (assuming the company is in top 12 Alexa ranking)?

**Comment by DavidMGross** [comment]
Do you want to keep this issue open as a way of accepting new submissions, or can we close it as resolved?

**Comment by devxoul** [comment]
StyleShare uses RxSwift and RxJava for apps.

* Website: https://www.stylesha.re
* Alexa Ranking: 56,814 (https://www.alexa.com/siteinfo/stylesha.re)
* Logo:

    ![styleshare-logo](https://user-images.githubusercontent.com/931655/30779942-f81e1628-a139-11e7-8641-ea3b154b6455.png)

**Comment by LanaIV** [comment]
Hello, I'd like to use Rx logo to create meetup presentation image: https://www.meetup.com/Reactive-Paris/. Can I use it without any legal issues or where can I ask authorization to use it. Thanks in advance.

**Comment by akarnokd** [comment]
Might not be relevant after so much time. If still, please open a new issue.
