### ISSUE TITLE
takeLast( number, timespan, units ) diagram / explanation incorrect?

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/reactivex.github.io#264]
This diagram:
![takeLast](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/takeLast.tn.png)

suggests that `takeLast( number, timespan, units)` will emit the first `number` items emitted during the last `timespan` period before the source Observable completes.

But ReactiveX/RxJava#4009 reports that it seems to emit the *last* `number` items emitted during that period.

If so, correct the marble diagram and make sure the text at http://reactivex.io/documentation/operators/takelast.html is accurate.

**Comment by akarnokd** [comment]
Yes, takeLast(1) returns the purple ball, takeLast(2) returns the blue followed by the purple balls.

**Comment by DavidMGross** [comment]
Fixed.
