### ISSUE TITLE
https://reactivex.io/ gives NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by jamesgorman2** [ReactiveX/reactivex.github.io#307]
Was poking around looking for an https site for `RxNetty` and found that https://reactivex.io/ has a bad cert.

Findings:
- https://reactivex.github.io/ redirects to http://reactivex.io/ 
- https://reactivex.io/ does not redirect but reports
  
  > NET::ERR_CERT_COMMON_NAME_INVALID
  > ...
  > This server could not prove that it is reactivex.io; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

Windows 10
Chrome Version 52.0.2743.116 m
Microsoft Edge 38.14393.0.0

**Comment by akarnokd** [comment]
Fixed awhile ago.
