### ISSUE TITLE
Fix footer and header for phones

### ISSUE THREAD

**Issue by staltz** [ReactiveX/reactivex.github.io#31]
On phones, the jumbotron background image should be statically positioned to perform better. Its height also needs to be improved.

This is how the footer looks on iPhone.
![ios simulator screen shot 11 sep 2014 11 43 10](https://cloud.githubusercontent.com/assets/90512/4234306/897ace6c-39b5-11e4-8bed-890355ad02a7.png)

I can fix this issue.

**Comment by DavidMGross** [comment]
Is this still a problem? (I don't have an iPhone to test with)
