### ISSUE TITLE
Documentation style guidelines

### ISSUE THREAD

**Issue by hamen** [ReactiveX/reactivex.github.io#310]
Hi all,

do we have guidelines for contributing to documentation? I'm thinking about adding a few paragraphs here and there, but every time I edit a file the editor messes up the formatting and I end up with 2 million changed lines diff for 4 lines I actually added 😂
Is there a style I can use in my editor and keep the diff to the minimum?

**Comment by DavidMGross** [comment]
I've done much of the editing so far. I just use a simple text editor (vi) that doesn't do much of anything in the way of styling, and so it does a good job of only making the edits I ask it to make. That's what I'd recommend.

Remember to make any changes to the "develop" branch, not the "master" branch.
