### ISSUE TITLE
History back button doesn't work

### ISSUE THREAD

**Issue by tomasbedrich** [ReactiveX/reactivex.github.io#311]
I am not 100% sure it is the issue of this repository, so sorry in advance, if not.

The problem appears when I go to API documentation of (for example) [a `concatMap()` method](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-concatMap) and then navigate to another method on the same page, for example [a `concatMapTo()` method](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-concatMapTo) without reloading the page (i.e. using a search).

Then I am not able to use a back button in my browser to get back to a `concatMap()` method. Only the URL changes, but the page doesn't scroll to the right method.

**Comment by DavidMGross** [comment]
Continued at: ReactiveX/rxjs#1989

(this repo doesn't cover the RxJS site)
