### ISSUE TITLE
404 links in the doc

### ISSUE THREAD

**Issue by tasomaniac** [ReactiveX/reactivex.github.io#326]
A blog post mentioned in `refcount` and `publish` from Kaushik is giving 404 now. 
The link from his personal blog is [here](http://blog.kaush.co/2015/01/21/rxjava-tip-for-the-day-share-publish-refcount-and-all-that-jazz/)

I was going to update them but I saw that they are available both in `documentation` folder and in `ko` folder. Should I update all of them? I didn't understand the `ko` folder. 

Thanks.

**Comment by DavidMGross** [comment]
The `ko` folder contains Korean-language translations of the documentation pages, so if you change the blog link URL, you should do so in both folders. Thanks for spotting & reporting this.
