### ISSUE TITLE
Close/Clean up the reactivex.github.io wiki

### ISSUE THREAD

**Issue by dwursteisen** [ReactiveX/reactivex.github.io#344]
Hello

The wiki from this repository (https://github.com/ReactiveX/reactivex.github.io/wiki) seems to be completly spammed

Maybe it should be closed at the "home" page doesn't give much information ?

**Comment by DavidMGross** [comment]
I deleted all of the spam, but can't figure out how to delete the wiki itself so that the spam doesn't return. What's the trick?

**Comment by dwursteisen** [comment]
You should be abble to uncheck "Wikis" in the settins of the repository. (on the repository page, the last tabs, after Pulse and Graphs should be setting)

this link should lead you to the settings page : https://github.com/ReactiveX/reactivex.github.io/settings

**Comment by DavidMGross** [comment]
Hmmm... I seem to have no such tab and that URL just sends me to the github 404 jedi.

**Comment by dwursteisen** [comment]
It should be because you're not the owner of the repository. I don't yet
any better explanation for the moment.

Le lun. 23 janv. 2017 18:44, David Gross <notifications@github.com> a
écrit :

**Comment by akarnokd** [comment]
Looks like the pages were deleted a long time ago. I locked down the wiki further to push-access only users.
