### ISSUE TITLE
Rx is not defined in browser developer tools console

### ISSUE THREAD

**Issue by samedson** [ReactiveX/reactivex.github.io#374]
It used to be the case that when you went to the reactive.io website, you could open up Chrome's developer tools, and `Rx` would be loaded in, acting as a really convenient playground to test out all the operators. This was an awesome feature and I found myself reaching for it constantly - I'm hoping that it will be added back.

I've checked the following sites:
https://rxjs-dev.firebaseapp.com/api
http://reactivex.io/

Here's a stackoverflow question that references the functionality:
[Question](https://stackoverflow.com/questions/49156682/how-do-i-use-rxjs-observable-in-chrome-or-firefox-developer-tools-console)

Thanks!

**Comment by akarnokd** [comment]
Looks like there is an updated answer to that SO question so just use that website they link to.
