### ISSUE TITLE
Please reactivex.io site secured (https).

### ISSUE THREAD

**Issue by dmitry-weirdo** [ReactiveX/reactivex.github.io#389]
As we see, http://reactivex.io/ is a non-secure, http site.

One of the inconvenient consequences is that when we try to view a Javadoc in IDEA, the images are not shown (probably because of my company's proxy-server, but anyway), so I have to go to the site in the browser.

It looks like this:
![image](https://user-images.githubusercontent.com/15837869/60666814-4735b400-9e68-11e9-8644-38d9d08cd54c.png)

The suggestion is to make site and links to images in javadocs secured.

**Comment by kennedy** [comment]
bump

**Comment by vietj** [comment]
bump, this makes javadoc linking from a secure web-site impossible

**Comment by AtosNicoS** [comment]
I recently also stumbled across this issue. What a shame that this is still http!

**Comment by ferrata** [comment]
Hey folks! Would be awesome to fix this issue.

![image](https://user-images.githubusercontent.com/31716295/124845797-114acf00-df5d-11eb-82da-dc2b3cbe7762.png)

**Comment by r3h0** [comment]
Duplicate of #355. See also #398, which indicates that this repo is no longer actively maintained.

**Comment by crstalli** [comment]
Https is allowed now; try testing to see if you are still experiencing issues. You can still navigate to the site insecurely, but https is supported now.

**Comment by akarnokd** [comment]
Should be working for some time now.
