### ISSUE TITLE
Is this repo still maintained

### ISSUE THREAD

**Issue by arkivanov** [ReactiveX/reactivex.github.io#398]
Issues are not being responded, PRs are not being reviewed...

**Comment by DavidMGross** [comment]
I'm no longer actively managing reactivex.github.io. We need to find others who can pick up my slack.

**Comment by akarnokd** [comment]
@r3h0 I don't have the knowledge to support this site and only the owner of the domain reactivex.io can fix the missing DNS records for HTTPS.

> which 404s without the direct link to the 3.x version

Not sure what you'd want to see at http://reactivex.io/RxJava .

**Comment by crstalli** [comment]
I believe issue [355](https://github.com/ReactiveX/reactivex.github.io/issues/355) will be closed; we are now able to navigate to the page using https.

**Comment by akarnokd** [comment]
The repo is maintainad again :tada:
