### ISSUE TITLE
Adding freak4pc to ReactiveX

### ISSUE THREAD

**Issue by kzaher** [ReactiveX/reactivex.github.io#407]
Hi,

I'm aware that this is not the best place to post this issue, but I don't know of any other and I don't have any means of contacting ReactiveX owners.

I unfortunately didn't have the capacity lately to maintain RxSwiftLang so @freak4pc has been the main maintainer of RxSwift repo for at least the past year https://github.com/ReactiveX/RxSwift/commits?author=freak4pc and has made an awesome job of taking care of the project. He has also been quite a prominent member of a community for as long as I can remember and he's been giving talks for a long time.

@abersnaze @asm89 @benjchristensen @benlesh @jhusain @mattpodwysocki @reactivexadmin  Would it be possible to give him at least some recognition for this work by inviting him to join the ReactiveX org?

**Comment by benjchristensen** [comment]
Hi, so if I understand correct, you would like to @freak4pc as an Admin, the same as you currently are @kzaher?

**Comment by freak4pc** [comment]
Thank you Ben :)

**Comment by kzaher** [comment]
>Hi, so if I understand correct, you would like to @freak4pc as an Admin, the same as you currently are @kzaher?
 
Yes please. Thanks Ben.

**Comment by akarnokd** [comment]
Looks like this has handled.
