### ISSUE TITLE
Add HTTPS to  reactivex.io

### ISSUE THREAD

**Issue by a45b** [ReactiveX/reactivex.github.io#409]
Can we just add an ssl? LetsEncrypt is there for free. 
Or we can host somewhere which gives it for free like GitHub-pages, netlify, vercel...etc.

**Comment by r3h0** [comment]
Duplicate of #355

**Comment by crstalli** [comment]
> Duplicate of #355

The site now supports https, although it is not enforced yet.

**Comment by akarnokd** [comment]
This started working some time ago so closing as completed.
