### ISSUE TITLE
Add Julia's Rocket.jl to reactivex.io

### ISSUE THREAD

**Issue by bvdmitri** [ReactiveX/reactivex.github.io#413]
We have implemented native reactive programming support in Julia programming language - [Rocket.jl](https://github.com/biaslab/Rocket.jl). It has been highly inspired by reactivex community, [concepts](https://biaslab.github.io/Rocket.jl/stable/getting-started/) and [function/operator names](https://biaslab.github.io/Rocket.jl/stable/operators/all/) were mostly directly translated to Julia's implementation. 

In terms of functionality Rocket.jl provides a much wider range of creation and modification operators, more different types of observables, provides different execution schedulers, and is more efficient than other libraries ([link for our JuliaCon presentation](https://www.youtube.com/watch?v=5UVwzzWeCm8)). 

The library exists for more than 2 years for now and is the most starred package for reactive programming that are used and maintained in Julia:
- [Rocket.jl](https://github.com/biaslab/Rocket.jl): 124 stars
- [Observables.jl](https://github.com/JuliaGizmos/Observables.jl): 72 stars
- [Signals.jl](https://github.com/TsurHerman/Signals.jl): 36 stars, last commit a year ago
- [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl), 172 stars, abandoned 😕, last release in 2018

In our opinion, to increase discoverability and support Julia developers it would be nice to add Rocket.jl on the [ReactiveX languages page](https://reactivex.io/languages.html) under Julia programming language.

**Comment by akarnokd** [comment]
Sure, please post a PR.

**Comment by bvdmitri** [comment]
A PR is ready #426
