### ISSUE TITLE
Frontpage details broken on some browser

### ISSUE THREAD

**Issue by staltz** [ReactiveX/reactivex.github.io#49]
I saw this from Ben's recently published presentation: 

![screen shot 2014-09-30 at 19 32 55](https://cloud.githubusercontent.com/assets/90512/4462074/b1cdb73a-48bf-11e4-811d-8c9d4cdff210.png)

There are a couple of things broken here: jumbotron arrow position, jumbotron height, and diagram arrow heads. Which browser were you using here, @benjchristensen ?

(I intend to fix these once I know)

**Comment by DavidMGross** [comment]
Clicking on the arrow or using right-arrow to page scroll still doesn't work (Chrome/OSX). Is that really an issue though? Is the arrow meant to be clickable or just to indicate there's more content below? Has a UI standard dialect emerged for page designs of this sort in which such an indicator is clickable or not?
