### ISSUE TITLE
Home Page Header Fills Page in Safari

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/reactivex.github.io#56]
The reactivex.io home page fills the entire browser window with the header.

![screen shot 2014-11-10 at 9 34 06 am](https://cloud.githubusercontent.com/assets/813492/4980384/d25e0418-68ff-11e4-9dce-ff25beafaff1.png)

**Comment by DavidMGross** [comment]
I'm going to chalk this up to modern web design trends, though I don't care for it much either.
