### ISSUE TITLE
Dynamic code sample tabs don't work in Firefox

### ISSUE THREAD

**Issue by GeorgiKhomeriki** [ReactiveX/reactivex.github.io#7]
In firefox version 30.0 (tested on OS X 10.8) the code sample tabs are not working correctly.
The tabs are created using Polymer custom tags (w/ paper tabs).
This issue can be observed on: http://reactivex.io/embed-test

**Comment by DavidMGross** [comment]
Is this still an issue? I notice that the link you supplied isn't giving code tabs in any of the browsers now. Seems that we may need to come up with another way of presenting such samples, perhaps the accordion method as used on the operator pages.

**Comment by GeorgiKhomeriki** [comment]
No, this is no longer an issue. We abandoned polymer altogether, since it only works properly on Chrome browsers. Accordion could be an alternative indeed.
