### ISSUE TITLE
Strange UI on IE 11

### ISSUE THREAD

**Issue by keilw** [ReactiveX/reactivex.github.io#98]
At least on IE 11 the site's UI looks everything other than "reactive". Menu items are hidden by the logo, don't think it is a desired effect? ;-)

![2015-02-18 14_37_34-reactivex - internet explorer 11](https://cloud.githubusercontent.com/assets/70496/6248081/faf32140-b77b-11e4-8859-f220c71b04ee.png)

**Comment by DavidMGross** [comment]
This is also being discussed at Issue #84

**Comment by DavidMGross** [comment]
Fixed in #100
